const images = [
    "A_simple_8-bit_pixel_art_design_of_a_Balearic_shea.png",
    "A_simple_8-bit_pixel_art_design_of_a_Eurasian_blac.png",
    "A_simple_8-bit_pixel_art_design_of_a_Eurasian_curl.png",
    "A_simple_8-bit_pixel_art_design_of_a_Eurasian_magp.png",
    "A_simple_8-bit_pixel_art_design_of_a_Eurasian_wren.png",
    "A_simple_8-bit_pixel_art_design_of_a_European_gold.png",
    "A_simple_8-bit_pixel_art_design_of_a_European_gree.png",
    "A_simple_8-bit_pixel_art_design_of_a_European_nigh.png",
    "A_simple_8-bit_pixel_art_design_of_a_European_robi.png",
    "A_simple_8-bit_pixel_art_design_of_a_European_star.png",
    "A_simple_8-bit_pixel_art_design_of_a_European_ston.png",
    "A_simple_8-bit_pixel_art_design_of_a_barn_owl_(Tyt.png",
    "A_simple_8-bit_pixel_art_design_of_a_bearded_tit_(.png",
    "A_simple_8-bit_pixel_art_design_of_a_black-headed_.png",
    "A_simple_8-bit_pixel_art_design_of_a_black-throate.png",
    "A_simple_8-bit_pixel_art_design_of_a_black_guillem.png",
    "A_simple_8-bit_pixel_art_design_of_a_black_redstar.png",
    "A_simple_8-bit_pixel_art_design_of_a_blackcap_(Syl.png",
    "A_simple_8-bit_pixel_art_design_of_a_blue_tit_(Cya.png",
    "A_simple_8-bit_pixel_art_design_of_a_brambling_(Fr.png",
    "A_simple_8-bit_pixel_art_design_of_a_carrion_crow_.png",
    "A_simple_8-bit_pixel_art_design_of_a_chaffinch_(Fr.png",
    "A_simple_8-bit_pixel_art_design_of_a_coal_tit_(Per.png",
    "A_simple_8-bit_pixel_art_design_of_a_collared_dove.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_blackb.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_crossb.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_kingfi.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_linnet.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_moorhe.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_redsha.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_sandpi.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_snipe_.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_swift_.png",
    "A_simple_8-bit_pixel_art_design_of_a_common_wood_p.png",
    "A_simple_8-bit_pixel_art_design_of_a_cormorant_(Ph.png",
    "A_simple_8-bit_pixel_art_design_of_a_corn_bunting_.png",
    "A_simple_8-bit_pixel_art_design_of_a_corncrake_(Cr.png",
    "A_simple_8-bit_pixel_art_design_of_a_cuckoo_(Cucul.png",
    "A_simple_8-bit_pixel_art_design_of_a_dusky_warbler.png",
    "A_simple_8-bit_pixel_art_design_of_a_firecrest_(Re.png",
    "A_simple_8-bit_pixel_art_design_of_a_goldfinch_(Ca.png",
    "A_simple_8-bit_pixel_art_design_of_a_great_crested.png",
    "A_simple_8-bit_pixel_art_design_of_a_great_spotted.png",
    "A_simple_8-bit_pixel_art_design_of_a_great_tit_(Pa.png",
    "A_simple_8-bit_pixel_art_design_of_a_grey_heron_(A.png",
    "A_simple_8-bit_pixel_art_design_of_a_hen_harrier_(.png",
    "A_simple_8-bit_pixel_art_design_of_a_herring_gull_.png",
    "A_simple_8-bit_pixel_art_design_of_a_house_sparrow.png",
    "A_simple_8-bit_pixel_art_design_of_a_jackdaw_(Corv.png",
    "A_simple_8-bit_pixel_art_design_of_a_kestrel_(Falc.png",
    "A_simple_8-bit_pixel_art_design_of_a_little_egret_.png",
    "A_simple_8-bit_pixel_art_design_of_a_little_owl_(A.png",
    "A_simple_8-bit_pixel_art_design_of_a_little_tern_(.png",
    "A_simple_8-bit_pixel_art_design_of_a_long-tailed_t.png",
    "A_simple_8-bit_pixel_art_design_of_a_mallard_duck_.png",
    "A_simple_8-bit_pixel_art_design_of_a_marsh_harrier.png",
    "A_simple_8-bit_pixel_art_design_of_a_meadow_pipit_.png",
    "A_simple_8-bit_pixel_art_design_of_a_mute_swan_(Cy.png",
    "A_simple_8-bit_pixel_art_design_of_a_northern_lapw.png",
    "A_simple_8-bit_pixel_art_design_of_a_northern_whea.png",
    "A_simple_8-bit_pixel_art_design_of_a_pallas's_warb.png",
    "A_simple_8-bit_pixel_art_design_of_a_peregrine_fal.png",
    "A_simple_8-bit_pixel_art_design_of_a_pied_wagtail_.png",
    "A_simple_8-bit_pixel_art_design_of_a_pomarine_skua.png",
    "A_simple_8-bit_pixel_art_design_of_a_red-backed_sh.png",
    "A_simple_8-bit_pixel_art_design_of_a_red-flanked_b.png",
    "A_simple_8-bit_pixel_art_design_of_a_red-throated_.png",
    "A_simple_8-bit_pixel_art_design_of_a_red_kite_(Mil.png",
    "A_simple_8-bit_pixel_art_design_of_a_redwing_(Turd.png",
    "A_simple_8-bit_pixel_art_design_of_a_reed_bunting_.png",
    "A_simple_8-bit_pixel_art_design_of_a_ring_ouzel_(T.png",
    "A_simple_8-bit_pixel_art_design_of_a_rook_(Corvus_.png",
    "A_simple_8-bit_pixel_art_design_of_a_roseate_tern_.png",
    "A_simple_8-bit_pixel_art_design_of_a_rustic_buntin.png",
    "A_simple_8-bit_pixel_art_design_of_a_sand_martin_(.png",
    "A_simple_8-bit_pixel_art_design_of_a_serin_(Serinu.png",
    "A_simple_8-bit_pixel_art_design_of_a_shag_(Gulosus.png",
    "A_simple_8-bit_pixel_art_design_of_a_shore_lark_(E.png",
    "A_simple_8-bit_pixel_art_design_of_a_skylark_(Alau.png",
    "A_simple_8-bit_pixel_art_design_of_a_snow_bunting_.png",
    "A_simple_8-bit_pixel_art_design_of_a_song_thrush_(.png",
    "A_simple_8-bit_pixel_art_design_of_a_spotted_flyca.png",
    "A_simple_8-bit_pixel_art_design_of_a_tawny_owl_(St.png",
    "A_simple_8-bit_pixel_art_design_of_a_tree_pipit_(A.png",
    "A_simple_8-bit_pixel_art_design_of_a_water_rail_(R.png",
    "A_simple_8-bit_pixel_art_design_of_a_whinchat_(Sax.png",
    "A_simple_8-bit_pixel_art_design_of_a_white-tailed_.png",
    "A_simple_8-bit_pixel_art_design_of_a_wood_warbler_.png",
    "A_simple_8-bit_pixel_art_design_of_a_woodcock_(Sco.png",
    "A_simple_8-bit_pixel_art_design_of_a_woodlark_(Lul.png",
    "A_simple_8-bit_pixel_art_design_of_a_yellow_wagtai.png",
    "A_simple_8-bit_pixel_art_of_a_Banded_Demoiselle_(C.png",
    "A_simple_8-bit_pixel_art_of_a_Beautiful_Demoiselle.png",
    "A_simple_8-bit_pixel_art_of_a_Broad-bodied_Chaser_.png",
    "A_simple_8-bit_pixel_art_of_a_Buff-tailed_Bumblebe.png",
    "A_simple_8-bit_pixel_art_of_a_Cave_Spider_(Meta_me.png",
    "A_simple_8-bit_pixel_art_of_a_Comma_butterfly_(Pol.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Blue_butterfl.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Crab_Spider_(.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Darter_dragon.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Fox_Spider_(A.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Frog_(Rana_te.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Lizard_(Zooto.png",
    "A_simple_8-bit_pixel_art_of_a_Common_Toad_(Bufo_bu.png",
    "A_simple_8-bit_pixel_art_of_a_Death_Cap_mushroom_(.png",
    "A_simple_8-bit_pixel_art_of_a_Devil’s_Coach_Horse_.png",
    "A_simple_8-bit_pixel_art_of_a_European_Adder_(Vipe.png",
    "A_simple_8-bit_pixel_art_of_a_European_Garden_Spid.png",
    "A_simple_8-bit_pixel_art_of_a_False_Black_Widow_Sp.png",
    "A_simple_8-bit_pixel_art_of_a_Fen_Raft_Spider_(Dol.png",
    "A_simple_8-bit_pixel_art_of_a_Fly_Agaric_mushroom_.png",
    "A_simple_8-bit_pixel_art_of_a_Grass_Snake_(Natrix_.png",
    "A_simple_8-bit_pixel_art_of_a_Great_Crested_Newt_(.png",
    "A_simple_8-bit_pixel_art_of_a_Hammock-web_Spider_(.png",
    "A_simple_8-bit_pixel_art_of_a_Harlequin_Ladybird_(.png",
    "A_simple_8-bit_pixel_art_of_a_Holly_Blue_butterfly.png",
    "A_simple_8-bit_pixel_art_of_a_Jelly_Ear_Fungus_(Au.png",
    "A_simple_8-bit_pixel_art_of_a_Lace_Web_Spider_(Ama.png",
    "A_simple_8-bit_pixel_art_of_a_Large_Red_Damselfly_.png",
    "A_simple_8-bit_pixel_art_of_a_Marmalade_Hoverfly_(.png",
    "A_simple_8-bit_pixel_art_of_a_Marsh_Frog_(Pelophyl.png",
    "A_simple_8-bit_pixel_art_of_a_Migrant_Hawker_drago.png",
    "A_simple_8-bit_pixel_art_of_a_Natterjack_Toad_(Epi.png",
    "A_simple_8-bit_pixel_art_of_a_Painted_Lady_butterf.png",
    "A_simple_8-bit_pixel_art_of_a_Palmate_Newt_(Lissot.png",
    "A_simple_8-bit_pixel_art_of_a_Panther_Cap_mushroom.png",
    "A_simple_8-bit_pixel_art_of_a_Peacock_butterfly_(A.png",
    "A_simple_8-bit_pixel_art_of_a_Raft_Spider_(Dolomed.png",
    "A_simple_8-bit_pixel_art_of_a_Red-tailed_Bumblebee.png",
    "A_simple_8-bit_pixel_art_of_a_Red_Admiral_butterfl.png",
    "A_simple_8-bit_pixel_art_of_a_Running_Crab_Spider_.png",
    "A_simple_8-bit_pixel_art_of_a_Sand_Lizard_(Lacerta.png",
    "A_simple_8-bit_pixel_art_of_a_Scarlet_Elf_Cup_fung.png",
    "A_simple_8-bit_pixel_art_of_a_Seven-spot_Ladybird_.png",
    "A_simple_8-bit_pixel_art_of_a_Shaggy_Inkcap_mushro.png",
    "A_simple_8-bit_pixel_art_of_a_Slow_Worm_(Anguis_fr.png",
    "A_simple_8-bit_pixel_art_of_a_Small_Tortoiseshell_.png",
    "A_simple_8-bit_pixel_art_of_a_Smooth_Snake_(Corone.png",
    "A_simple_8-bit_pixel_art_of_a_Southern_Hawker_drag.png",
    "A_simple_8-bit_pixel_art_of_a_Speckled_Wood_butter.png",
    "A_simple_8-bit_pixel_art_of_a_Stag_Beetle_(Lucanus.png",
    "A_simple_8-bit_pixel_art_of_a_Stinkhorn_fungus_(Ph.png",
    "A_simple_8-bit_pixel_art_of_a_Stripe-legged_Spider.png",
    "A_simple_8-bit_pixel_art_of_a_Thick-legged_Flower_.png",
    "A_simple_8-bit_pixel_art_of_a_Tree_Bumblebee_(Bomb.png",
    "A_simple_8-bit_pixel_art_of_a_Wall_Lizard_(Podarci.png",
    "A_simple_8-bit_pixel_art_of_an_Alpine_Newt_(Ichthy.png",
    "A_simple_8-bit_pixel_art_of_an_Edible_Frog_(Peloph.png",
    "A_simple_8-bit_pixel_art_of_an_Emperor_Dragonfly_(.png",
    "A_simple_8-bit_pixel_art_of_an_Orange_Peel_Fungus_.png",
    "DALL·E 2025-02-17 16.36.30 - A simple 8-bit pixel art design of a common dandelion (Taraxacum officinale). Bright yellow flower with jagged green leaves, depicted in pixel art sty.webp",
    "DALL·E 2025-02-17 16.36.45 - A very simple 8-bit pixel art design of an English oak (Quercus robur). Green leafy tree with a brown trunk, depicted in minimal pixel detail typical .webp",
    "DALL·E 2025-02-17 16.36.47 - A very simple 8-bit pixel art design of a common nettle (Urtica dioica). Green jagged leaves with minimal pixel detail, classic 8-bit style.webp",
    "DALL·E 2025-02-17 16.36.49 - A very simple 8-bit pixel art design of an English bluebell (Hyacinthoides non-scripta). Small purple-blue flowers hanging from a curved green stem in.webp",
    "DALL·E 2025-02-17 16.36.51 - A very simple 8-bit pixel art design of a common daisy (Bellis perennis). White petals surrounding a yellow center with minimal pixel detail in classi.webp",
    "DALL·E 2025-02-17 16.36.53 - A very simple 8-bit pixel art design of a foxglove (Digitalis purpurea). Tall purple tubular flowers in a vertical row with green leaves, minimal pixe.webp",
    "DALL·E 2025-02-17 16.36.56 - A very simple 8-bit pixel art design of a common poppy (Papaver rhoeas). Bright red flower with a black center and green stem, minimal pixel detail, c.webp",
    "DALL·E 2025-02-17 16.36.58 - A very simple 8-bit pixel art design of an elderflower (Sambucus nigra). Small white flower clusters with green leaves, minimal pixel detail, classic .webp",
    "DALL·E 2025-02-17 16.37.01 - A very simple 8-bit pixel art design of a field buttercup (Ranunculus acris). Bright yellow flower with five petals and green leaves, minimal pixel de.webp",
    "DALL·E 2025-02-17 16.37.03 - A very simple 8-bit pixel art design of a hawthorn (Crataegus monogyna). Small white flowers with green leaves, minimal pixel detail, classic 8-bit st.webp",
    "DALL·E 2025-02-17 16.37.06 - A very simple 8-bit pixel art design of a silver birch (Betula pendula). Tall tree with white bark and sparse green leaves, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.37.08 - A very simple 8-bit pixel art design of a wild garlic (Allium ursinum). Small white star-shaped flowers with long green leaves, minimal pixel detail, .webp",
    "DALL·E 2025-02-17 16.37.10 - A very simple 8-bit pixel art design of a yarrow (Achillea millefolium). Small white clustered flowers with fern-like green leaves, minimal pixel deta.webp",
    "DALL·E 2025-02-17 16.37.12 - A very simple 8-bit pixel art design of a lesser celandine (Ficaria verna). Bright yellow star-shaped flower with green heart-shaped leaves, minimal p.webp",
    "DALL·E 2025-02-17 16.37.17 - A very simple 8-bit pixel art design of a field scabious (Knautia arvensis). Pale purple pincushion-like flower with green leaves, minimal pixel detai.webp",
    "DALL·E 2025-02-17 16.37.20 - A very simple 8-bit pixel art design of a blackthorn (Prunus spinosa). Small white flowers on spiny dark branches with minimal pixel detail, classic 8.webp",
    "DALL·E 2025-02-17 16.37.22 - A very simple 8-bit pixel art design of a bird’s-foot trefoil (Lotus corniculatus). Small yellow flowers with green leaves, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.37.24 - A very simple 8-bit pixel art design of a corn marigold (Glebionis segetum). Bright yellow daisy-like flower with green leaves, minimal pixel detail, .webp",
    "DALL·E 2025-02-17 16.37.27 - A very simple 8-bit pixel art design of a cuckoo flower (Cardamine pratensis). Pale lilac four-petaled flowers with green leaves, minimal pixel detail.webp",
    "DALL·E 2025-02-17 16.37.29 - A very simple 8-bit pixel art design of a dog violet (Viola riviniana). Small purple flower with green leaves, minimal pixel detail, classic 8-bit sty.webp",
    "DALL·E 2025-02-17 16.37.32 - A very simple 8-bit pixel art design of a common ragwort (Jacobaea vulgaris). Bright yellow cluster of flowers with green leaves, minimal pixel detail.webp",
    "DALL·E 2025-02-17 16.37.34 - A very simple 8-bit pixel art design of a common hogweed (Heracleum sphondylium). White umbrella-like flower clusters with green leaves, minimal pixel.webp",
    "DALL·E 2025-02-17 16.37.50 - A very simple 8-bit pixel art design of a red campion (Silene dioica). Bright pink five-petaled flower with green leaves, minimal pixel detail, classi.webp",
    "DALL·E 2025-02-17 16.37.53 - A very simple 8-bit pixel art design of a cornflower (Centaurea cyanus). Bright blue flower with spiky petals and green leaves, minimal pixel detail, .webp",
    "DALL·E 2025-02-17 16.37.55 - A very simple 8-bit pixel art design of a wood anemone (Anemone nemorosa). White flower with six petals and green leaves, minimal pixel detail, classi.webp",
    "DALL·E 2025-02-17 16.38.02 - A very simple 8-bit pixel art design of a wild pansy (Viola tricolor). Purple, yellow, and white flowers with green leaves, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.38.04 - A very simple 8-bit pixel art design of a bugle (Ajuga reptans). Purple-blue flowers in a spike with green leaves, minimal pixel detail, classic 8-bit.webp",
    "DALL·E 2025-02-17 16.38.08 - A very simple 8-bit pixel art design of a lady's bedstraw (Galium verum). Small yellow flowers in clusters with thin green leaves, minimal pixel detai.webp",
    "DALL·E 2025-02-17 16.38.11 - A very simple 8-bit pixel art design of a wood sorrel (Oxalis acetosella). Small white flowers with pink veins and green clover-like leaves, minimal p.webp",
    "DALL·E 2025-02-17 16.38.14 - A very simple 8-bit pixel art design of a common mallow (Malva sylvestris). Purple flowers with darker veins and green leaves, minimal pixel detail, c.webp",
    "DALL·E 2025-02-17 16.38.17 - A very simple 8-bit pixel art design of a herb robert (Geranium robertianum). Small pink five-petaled flowers with green leaves, minimal pixel detail,.webp",
    "DALL·E 2025-02-17 16.38.20 - A very simple 8-bit pixel art design of a marsh cinquefoil (Comarum palustre). Dark red star-shaped flower with green leaves, minimal pixel detail, cl.webp",
    "DALL·E 2025-02-17 16.38.32 - A very simple 8-bit pixel art design of a water mint (Mentha aquatica). Small purple-pink flower clusters with green round leaves, minimal pixel detai.webp",
    "DALL·E 2025-02-17 16.38.35 - A very simple 8-bit pixel art design of a wild primrose (Primula vulgaris). Pale yellow flowers with green leaves, minimal pixel detail, classic 8-bit.webp",
    "DALL·E 2025-02-17 16.38.38 - A very simple 8-bit pixel art design of a wild strawberry (Fragaria vesca). Small white flowers with yellow centers and green leaves, minimal pixel de.webp",
    "DALL·E 2025-02-17 16.38.42 - A very simple 8-bit pixel art design of a wild carrot (Daucus carota). Small white umbrella-shaped flower clusters with green leaves, minimal pixel de.webp",
    "DALL·E 2025-02-17 16.38.48 - A very simple 8-bit pixel art design of a greater knapweed (Centaurea scabiosa). Purple spiky flower head with green leaves, minimal pixel detail, cla.webp",
    "DALL·E 2025-02-17 16.38.55 - A very simple 8-bit pixel art design of a wild marjoram (Origanum vulgare). Small purple flowers with green leaves, minimal pixel detail, classic 8-bi.webp",
    "DALL·E 2025-02-17 16.38.58 - A very simple 8-bit pixel art design of a common dogwood (Cornus sanguinea). Small white flowers with green leaves, minimal pixel detail, classic 8-bi.webp",
    "DALL·E 2025-02-17 16.39.07 - A very simple 8-bit pixel art design of a wild basil (Clinopodium vulgare). Small purple flowers with green leaves, minimal pixel detail, classic 8-bi.webp",
    "DALL·E 2025-02-17 16.39.10 - A very simple 8-bit pixel art design of a betony (Betonica officinalis). Purple spike-like flowers with green leaves, minimal pixel detail, classic 8-.webp",
    "DALL·E 2025-02-17 16.39.13 - A very simple 8-bit pixel art design of a common knapweed (Centaurea nigra). Purple thistle-like flower with green leaves, minimal pixel detail, class.webp",
    "DALL·E 2025-02-17 16.39.16 - A very simple 8-bit pixel art design of a harebell (Campanula rotundifolia). Delicate blue bell-shaped flowers with thin green stems, minimal pixel de.webp",
    "DALL·E 2025-02-17 16.39.22 - A very simple 8-bit pixel art design of a meadow vetchling (Lathyrus pratensis). Small bright yellow pea-like flowers with green leaves, minimal pixel.webp",
    "DALL·E 2025-02-17 16.39.25 - A very simple 8-bit pixel art design of a wild onion (Allium vineale). Small round cluster of purple flowers with thin green leaves, minimal pixel det.webp",
    "DALL·E 2025-02-17 16.39.29 - A very simple 8-bit pixel art design of a common eyebright (Euphrasia officinalis). Small white flowers with purple veins and yellow centers, minimal .webp",
    "DALL·E 2025-02-17 16.39.31 - A very simple 8-bit pixel art design of a common hemp-nettle (Galeopsis tetrahit). Small purple flowers with green leaves, minimal pixel detail, class.webp",
    "DALL·E 2025-02-17 16.39.34 - A very simple 8-bit pixel art design of a wild thyme (Thymus polytrichus). Small purple flowers with green leaves, minimal pixel detail, classic 8-bit.webp",
    "DALL·E 2025-02-17 16.39.37 - A very simple 8-bit pixel art design of a yellow rattle (Rhinanthus minor). Small yellow flowers with green leaves, minimal pixel detail, classic 8-bi.webp",
    "DALL·E 2025-02-17 16.39.40 - A very simple 8-bit pixel art design of a wild angelica (Angelica sylvestris). White or pale pink umbrella-like flower clusters with green leaves, min.webp",
    "DALL·E 2025-02-17 16.39.43 - A very simple 8-bit pixel art design of a meadowsweet (Filipendula ulmaria). Small creamy-white flower clusters with green leaves, minimal pixel detai.webp",
    "DALL·E 2025-02-17 16.39.50 - A very simple 8-bit pixel art design of a marsh woundwort (Stachys palustris). Small purple flowers with green leaves, minimal pixel detail, classic 8.webp",
    "DALL·E 2025-02-17 16.39.53 - A very simple 8-bit pixel art design of a wild clary (Salvia verbenaca). Small purple-blue flowers with green leaves, minimal pixel detail, classic 8-.webp",
    "DALL·E 2025-02-17 16.39.56 - A very simple 8-bit pixel art design of a wood avens (Geum urbanum). Small yellow flowers with green leaves, minimal pixel detail, classic 8-bit style.webp",
    "DALL·E 2025-02-17 16.40.00 - A very simple 8-bit pixel art design of a sneezewort (Achillea ptarmica). Small white daisy-like flowers with green leaves, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.40.03 - A very simple 8-bit pixel art design of a common bistort (Persicaria bistorta). Pink spike-like flower with green leaves, minimal pixel detail, classi.webp",
    "DALL·E 2025-02-17 16.40.06 - A very simple 8-bit pixel art design of a common mouse-ear (Cerastium fontanum). Small white flowers with green leaves, minimal pixel detail, classic .webp",
    "DALL·E 2025-02-17 16.40.12 - A very simple 8-bit pixel art design of a purple loosestrife (Lythrum salicaria). Tall spikes of purple flowers with green leaves, minimal pixel detai.webp",
    "DALL·E 2025-02-17 16.40.15 - A very simple 8-bit pixel art design of a wild parsnip (Pastinaca sativa). Yellow umbrella-shaped flower clusters with green leaves, minimal pixel det.webp",
    "DALL·E 2025-02-17 16.40.18 - A very simple 8-bit pixel art design of a marsh violet (Viola palustris). Small purple flowers with green heart-shaped leaves, minimal pixel detail, c.webp",
    "DALL·E 2025-02-17 16.40.22 - A very simple 8-bit pixel art design of a wild honeysuckle (Lonicera periclymenum). Creamy white and pink flowers with green leaves, minimal pixel det.webp",
    "DALL·E 2025-02-17 16.40.28 - A very simple 8-bit pixel art design of a great burnet (Sanguisorba officinalis). Dark red globe-shaped flower heads with green leaves, minimal pixel .webp",
    "DALL·E 2025-02-17 16.40.32 - A very simple 8-bit pixel art design of a sea holly (Eryngium maritimum). Blue-green spiky flowers with silver-gray leaves, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.40.35 - A very simple 8-bit pixel art design of a common spotted orchid (Dactylorhiza fuchsii). Purple-pink flowers with darker spots and green leaves, minima.webp",
    "DALL·E 2025-02-17 16.40.38 - A very simple 8-bit pixel art design of a yellow iris (Iris pseudacorus). Bright yellow flowers with green sword-shaped leaves, minimal pixel detail, .webp",
    "DALL·E 2025-02-17 16.40.41 - A very simple 8-bit pixel art design of a white dead-nettle (Lamium album). White hooded flowers with green leaves, minimal pixel detail, classic 8-bi.webp",
    "DALL·E 2025-02-17 16.40.43 - A very simple 8-bit pixel art design of a common valerian (Valeriana officinalis). Pink flower clusters with green leaves, minimal pixel detail, class.webp",
    "DALL·E 2025-02-17 16.40.46 - A very simple 8-bit pixel art design of a yellow archangel (Lamium galeobdolon). Yellow hooded flowers with green leaves, minimal pixel detail, classi.webp",
    "DALL·E 2025-02-17 16.40.49 - A very simple 8-bit pixel art design of a meadow cranesbill (Geranium pratense). Blue-purple five-petaled flowers with green leaves, minimal pixel det.webp",
    "DALL·E 2025-02-17 16.40.52 - A very simple 8-bit pixel art design of a common toadflax (Linaria vulgaris). Small yellow and orange snapdragon-like flowers with green leaves, minim.webp",
    "DALL·E 2025-02-17 16.40.55 - A very simple 8-bit pixel art design of a common cat’s-ear (Hypochaeris radicata). Yellow dandelion-like flowers with green leaves, minimal pixel deta.webp",
    "DALL·E 2025-02-17 16.40.59 - A very simple 8-bit pixel art design of a common centaury (Centaurium erythraea). Small pink five-petaled flowers with green leaves, minimal pixel det.webp",
    "DALL·E 2025-02-17 16.41.18 - A very simple 8-bit pixel art design of a marsh marigold (Caltha palustris). Bright yellow cup-shaped flowers with green leaves, minimal pixel detail,.webp",
    "DALL·E 2025-02-17 16.41.34 - A very simple 8-bit pixel art design of a sea thrift (Armeria maritima). Small pink clustered flowers with green grass-like leaves, minimal pixel deta.webp",
    "DALL·E 2025-02-17 16.41.38 - A very simple 8-bit pixel art design of a common fleabane (Pulicaria dysenterica). Yellow daisy-like flowers with green leaves, minimal pixel detail, .webp",
    "DALL·E 2025-02-17 16.41.40 - A very simple 8-bit pixel art design of a common broom (Cytisus scoparius). Small yellow flowers on green branches, minimal pixel detail, classic 8-bi.webp",
    "DALL·E 2025-02-17 16.41.43 - A very simple 8-bit pixel art design of a marsh horsetail (Equisetum palustre). Small green segmented stems with thin leaves, minimal pixel detail, cl.webp",
    "DALL·E 2025-02-17 16.41.45 - A very simple 8-bit pixel art design of a common water-crowfoot (Ranunculus aquatilis). Small white flowers on green stems, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.41.53 - A very simple 8-bit pixel art design of a greater stitchwort (Stellaria holostea). White star-shaped flowers with green leaves, minimal pixel detail, .webp",
    "DALL·E 2025-02-17 16.42.04 - A very simple 8-bit pixel art design of a self-heal (Prunella vulgaris). Small purple flowers on a green stem with green leaves, minimal pixel detail,.webp",
    "DALL·E 2025-02-17 16.42.07 - A very simple 8-bit pixel art design of a common milkwort (Polygala vulgaris). Small blue or purple flowers with green leaves, minimal pixel detail, c.webp",
    "DALL·E 2025-02-17 16.42.23 - A very simple 8-bit pixel art design of a green alkanet (Pentaglottis sempervirens). Blue flowers with green leaves, minimal pixel detail, classic 8-b.webp",
    "DALL·E 2025-02-17 16.42.26 - A very simple 8-bit pixel art design of a red dead-nettle (Lamium purpureum). Small pinkish-purple flowers with green leaves, minimal pixel detail, cl.webp",
    "DALL·E 2025-02-17 16.42.28 - A very simple 8-bit pixel art design of a germander speedwell (Veronica chamaedrys). Bright blue flowers with green leaves, minimal pixel detail, clas.webp",
    "DALL·E 2025-02-17 16.42.31 - A very simple 8-bit pixel art design of a hedge bindweed (Calystegia sepium). White trumpet-shaped flowers with green leaves, minimal pixel detail, cl.webp",
    "DALL·E 2025-02-17 16.42.37 - A very simple 8-bit pixel art design of a common chickweed (Stellaria media). Small white star-shaped flowers with green leaves, minimal pixel detail,.webp",
    "DALL·E 2025-02-17 16.42.41 - A very simple 8-bit pixel art design of a wild radish (Raphanus raphanistrum). Pale yellow or lilac flowers with green leaves, minimal pixel detail, c.webp",
    "DALL·E 2025-02-17 16.42.45 - A very simple 8-bit pixel art design of a spearmint (Mentha spicata). Green serrated leaves with minimal pixel detail, classic 8-bit style.webp",
    "DALL·E 2025-02-17 16.42.48 - A very simple 8-bit pixel art design of a greater willowherb (Epilobium hirsutum). Pinkish-purple flowers with green leaves, minimal pixel detail, cla.webp",
    "DALL·E 2025-02-17 16.42.51 - A very simple 8-bit pixel art design of a silverweed (Potentilla anserina). Yellow flowers with silky silver-green leaves, minimal pixel detail, class.webp",
    "DALL·E 2025-02-17 16.43.08 - A very simple 8-bit pixel art design of a greater plantain (Plantago major). Wide green leaves with flower spikes, minimal pixel detail, classic 8-bit.webp",
    "DALL·E 2025-02-20 20.59.21 - Create a very simple 8-bit pixel art design of Sciurus carolinensis (Eastern grey squirrel) with minimal pixel detail, a bushy tail, and grey fur. Cla.webp",
    "DALL·E 2025-02-20 20.59.26 - Create a very simple 8-bit pixel art design of Erinaceus europaeus (European hedgehog) with minimal pixel detail, spiky quills, and a small snout. Cla.webp",
    "DALL·E 2025-02-20 20.59.29 - Create a very simple 8-bit pixel art design of Pipistrellus pygmaeus (soprano pipistrelle bat) with minimal pixel detail, small wings, large ears, and.webp",
    "DALL·E 2025-02-20 20.59.31 - Create a very simple 8-bit pixel art design of Pipistrellus pipistrellus (common pipistrelle bat) with minimal pixel detail, small wings, darker brown.webp",
    "DALL·E 2025-02-20 20.59.34 - Create a very simple 8-bit pixel art design of Sciurus vulgaris (red squirrel) with minimal pixel detail, reddish fur, tufted ears, and a bushy tail. .webp",
    "DALL·E 2025-02-20 20.59.36 - Create a very simple 8-bit pixel art design of Oryctolagus cuniculus (European rabbit) with minimal pixel detail, soft grey fur, long ears, and small .webp",
    "DALL·E 2025-02-20 20.59.39 - Create a very simple 8-bit pixel art design of Vulpes vulpes (red fox) with minimal pixel detail, orange-red fur, white underbelly, pointed ears, and .webp",
    "DALL·E 2025-02-20 20.59.42 - Create a very simple 8-bit pixel art design of Lepus europaeus (European hare) with minimal pixel detail, long ears with black tips, strong hind legs,.webp",
    "DALL·E 2025-02-20 20.59.45 - Create a very simple 8-bit pixel art design of Meles meles (European badger) with minimal pixel detail, black and white striped face, short legs, and .webp",
    "DALL·E 2025-02-20 20.59.48 - Create a very simple 8-bit pixel art design of Capreolus capreolus (roe deer) with minimal pixel detail, slender brown body, short antlers (for males).webp",
    "DALL·E 2025-02-20 20.59.51 - Create a very simple 8-bit pixel art design of Talpa europaea (European mole) with minimal pixel detail, dark fur, short limbs, large spade-like front.webp",
    "DALL·E 2025-02-20 20.59.54 - Create a very simple 8-bit pixel art design of Lutra lutra (European otter) with minimal pixel detail, sleek brown fur, long body, short legs, and whi.webp",
    "DALL·E 2025-02-20 20.59.57 - Create a very simple 8-bit pixel art design of Arvicola amphibius (European water vole) with minimal pixel detail, round brown body, small ears, short.webp",
    "DALL·E 2025-02-20 21.00.00 - Create a very simple 8-bit pixel art design of Chiroptera (bat) with minimal pixel detail, outstretched wings, small body, large ears, and dark brown .webp",
    "DALL·E 2025-02-20 21.00.04 - Create a very simple 8-bit pixel art design of Muscardinus avellanarius (hazel dormouse) with minimal pixel detail, golden-brown fur, bushy tail, larg.webp",
    "DALL·E 2025-02-20 21.00.08 - Create a very simple 8-bit pixel art design of Apodemus sylvaticus (wood mouse) with minimal pixel detail, small brown body, large ears, long tail, an.webp",
    "DALL·E 2025-02-20 21.00.18 - Create a very simple 8-bit pixel art design of Castor fiber (Eurasian beaver) with minimal pixel detail, brown fur, flat tail, and large front teeth. .webp",
    "DALL·E 2025-02-20 21.00.21 - Create a very simple 8-bit pixel art design of Rattus norvegicus (brown rat) with minimal pixel detail, grey-brown fur, long tail, small ears, and whi.webp",
    "DALL·E 2025-02-20 21.00.24 - Create a very simple 8-bit pixel art design of Rhinolophus hipposideros (lesser horseshoe bat) with minimal pixel detail, small brown body, wide wings.webp",
    "DALL·E 2025-02-20 21.00.28 - Create a very simple 8-bit pixel art design of Plecotus auritus (brown long-eared bat) with minimal pixel detail, brown fur, large prominent ears, and.webp",
    "DALL·E 2025-02-20 21.00.31 - Create a very simple 8-bit pixel art design of Muntiacus reevesi (Reeves's muntjac) with minimal pixel detail, small deer-like body, reddish-brown fur.webp",
    "DALL·E 2025-02-20 21.00.35 - Create a very simple 8-bit pixel art design of Cervus elaphus (red deer) with minimal pixel detail, large body, brown fur, and branched antlers. Class.webp",
    "DALL·E 2025-02-20 21.00.38 - Create a very simple 8-bit pixel art design of Nyctalus noctula (noctule bat) with minimal pixel detail, large brown body, wide wings, and small ears.webp",
    "DALL·E 2025-02-20 21.00.40 - Create a very simple 8-bit pixel art design of Sorex minutus (pygmy shrew) with minimal pixel detail, tiny brown body, pointed snout, and short tail. .webp",
    "DALL·E 2025-02-20 21.00.44 - Create a very simple 8-bit pixel art design of Halichoerus grypus (grey seal) with minimal pixel detail, grey mottled body, large flippers, and whiske.webp",
    "DALL·E 2025-02-20 21.00.47 - Create a very simple 8-bit pixel art design of Mustela erminea (stoat) with minimal pixel detail, slender brown body, white underbelly, and black-tipp.webp",
    "DALL·E 2025-02-20 21.00.50 - Create a very simple 8-bit pixel art design of Myotis nattereri (Natterer's bat) with minimal pixel detail, light brown fur, wide wings, and a pale un.webp",
    "DALL·E 2025-02-20 21.00.53 - Create a very simple 8-bit pixel art design of Phocoena phocoena (harbour porpoise) with minimal pixel detail, small streamlined body, dark grey back,.webp",
    "DALL·E 2025-02-20 21.00.56 - Create a very simple 8-bit pixel art design of Pipistrellus (pipistrelle bat genus) with minimal pixel detail, small dark body, wide wings, and large .webp",
    "DALL·E 2025-02-20 21.01.00 - Create a very simple 8-bit pixel art design of Microtus agrestis (field vole) with minimal pixel detail, small round brown body, short tail, and tiny .webp",
    "DALL·E 2025-02-20 21.01.20 - Create a very simple 8-bit pixel art design of Myodes glareolus (bank vole) with minimal pixel detail, small reddish-brown body, short tail, and round.webp",
    "DALL·E 2025-02-20 21.01.23 - Create a very simple 8-bit pixel art design of Sorex araneus (common shrew) with minimal pixel detail, small brown body, pointed snout, short tail, an.webp",
    "DALL·E 2025-02-20 21.01.25 - Create a very simple 8-bit pixel art design of Phoca vitulina (harbour seal) with minimal pixel detail, small grey body, flippers, round head with whi.webp",
    "DALL·E 2025-02-20 21.01.28 - Create a very simple 8-bit pixel art design of Myotis (mouse-eared bats) with minimal pixel detail, small brown body, wide wings, and large ears. Clas.webp",
    "DALL·E 2025-02-20 21.01.30 - Create a very simple 8-bit pixel art design of Neovison vison (American mink) with minimal pixel detail, slender dark brown body, short legs, small ea.webp",
    "DALL·E 2025-02-20 21.01.33 - Create a very simple 8-bit pixel art design of Dama dama (fallow deer) with minimal pixel detail, slender brown body with white spots, broad flattened.webp",
    "DALL·E 2025-02-20 21.01.35 - Create a very simple 8-bit pixel art design of Mustela nivalis (weasel) with minimal pixel detail, slender brown body, white underbelly, short legs, a.webp",
    "DALL·E 2025-02-20 21.01.38 - Create a very simple 8-bit pixel art design of Rhinolophus ferrumequinum (greater horseshoe bat) with minimal pixel detail, brown body, large wings, a.webp",
    "DALL·E 2025-02-20 21.01.40 - Create a very simple 8-bit pixel art design of Mammalia (mammals) with minimal pixel detail, a generic mammal figure such as a small brown quadruped w.webp",
    "DALL·E 2025-02-20 21.01.44 - Create a very simple 8-bit pixel art design of Tursiops truncatus (bottlenose dolphin) with minimal pixel detail, streamlined grey body, lighter under.webp",
    "DALL·E 2025-02-20 21.01.47 - Create a very simple 8-bit pixel art design of Lepus timidus (mountain hare) with minimal pixel detail, grey-brown fur (or white in winter), long ears.webp",
    "DALL·E 2025-02-20 21.01.50 - Create a very simple 8-bit pixel art design of Martes martes (pine marten) with minimal pixel detail, slender brown body, bushy tail, and distinctive .webp",
    "DALL·E 2025-02-20 21.01.55 - Create a very simple 8-bit pixel art design of Mustela putorius (European polecat) with minimal pixel detail, dark brown body, pale facial mask, short.webp",
    "DALL·E 2025-02-20 21.01.57 - Create a very simple 8-bit pixel art design of Eptesicus serotinus (serotine bat) with minimal pixel detail, large dark wings, brown body, and short r.webp",
    "DALL·E 2025-02-20 21.02.02 - Create a very simple 8-bit pixel art design of Nyctalus leisleri (Leisler’s bat) with minimal pixel detail, small brown body, broad dark wings, and sh.webp",
    "DALL·E 2025-02-20 21.02.04 - Create a very simple 8-bit pixel art design of Apodemus flavicollis (yellow-necked mouse) with minimal pixel detail, small brown body, yellowish band .webp",
    "DALL·E 2025-02-20 21.02.07 - Create a very simple 8-bit pixel art design of Arvicolinae (voles) with minimal pixel detail, small round brown body, short tail, tiny ears, and whisk.webp",
    "DALL·E 2025-02-20 21.02.11 - Create a very simple 8-bit pixel art design of Micromys minutus (harvest mouse) with minimal pixel detail, small golden-brown body, long prehensile ta.webp",
    "DALL·E 2025-02-20 21.02.13 - Create a very simple 8-bit pixel art design of Plecotus (long-eared bats) with minimal pixel detail, small brown body, large prominent ears, and outst.webp",
    "DALL·E 2025-02-20 21.02.16 - Create a very simple 8-bit pixel art design of Neomys fodiens (Eurasian water shrew) with minimal pixel detail, small black body, white underside, poi.webp",
    "DALL·E 2025-02-20 21.02.19 - Create a very simple 8-bit pixel art design of Hydropotes inermis (Chinese water deer) with minimal pixel detail, small light brown body, short legs, .webp",
    "DALL·E 2025-02-20 21.02.22 - Create a very simple 8-bit pixel art design of Mus musculus (house mouse) with minimal pixel detail, small grey body, large round ears, long tail, and.webp",
    "DALL·E 2025-02-20 21.02.24 - Create a very simple 8-bit pixel art design of Myotis mystacinus_brandtii (whiskered_Brandt’s bat) with minimal pixel detail, small brown body, large .webp",
    "DALL·E 2025-02-20 21.02.27 - Create a very simple 8-bit pixel art design of Myotis mystacinus (whiskered bat) with minimal pixel detail, small brown body, wide wings, and short ea.webp",
    "DALL·E 2025-02-20 21.02.30 - Create a very simple 8-bit pixel art design of Balaenoptera acutorostrata (minke whale) with minimal pixel detail, streamlined dark grey body, lighter.webp",
    "DALL·E 2025-02-20 21.02.32 - Create a very simple 8-bit pixel art design of Delphinus delphis (common dolphin) with minimal pixel detail, streamlined body, dark grey back, white u.webp",
    "DALL·E 2025-02-20 21.02.35 - Create a very simple 8-bit pixel art design of Barbastella barbastellus (barbastelle bat) with minimal pixel detail, small dark body, broad wings, and.webp",
    "DALL·E 2025-02-20 21.02.37 - Create a very simple 8-bit pixel art design of Soricidae (shrews) with minimal pixel detail, small grey body, pointed snout, tiny legs, and short tail.webp",
    "DALL·E 2025-02-20 21.02.40 - Create a very simple 8-bit pixel art design of Cervus nippon (sika deer) with minimal pixel detail, slender brown body with white spots, short antlers.webp",
    "DALL·E 2025-02-20 21.02.44 - Create a very simple 8-bit pixel art design of Felis silvestris (European wildcat) with minimal pixel detail, striped grey-brown fur, bushy tail with .webp",
    "DALL·E 2025-02-20 21.02.48 - Create a very simple 8-bit pixel art design of Cervidae (deer family) with minimal pixel detail, a generic deer figure with brown fur, short antlers, .webp",
    "DALL·E 2025-02-20 21.02.51 - Create a very simple 8-bit pixel art design of Pinnipedia (seals, sea lions, walruses) with minimal pixel detail, a generic seal figure with grey body.webp",
    "DALL·E 2025-02-20 21.02.53 - Create a very simple 8-bit pixel art design of Myocastor coypus (coypu) with minimal pixel detail, brown body, large front teeth, long tail, and webbe.webp",
    "DALL·E 2025-02-20 21.02.57 - Create a very simple 8-bit pixel art design of Pipistrellus nathusii (Nathusius’ pipistrelle) with minimal pixel detail, small brown body, broad wings.webp",
    "DALL·E 2025-02-20 21.03.00 - Create a very simple 8-bit pixel art design of Capra hircus (domestic goat) with minimal pixel detail, small white or brown body, short curved horns, .webp",
    "DALL·E 2025-02-20 21.03.05 - Create a very simple 8-bit pixel art design of Vespertilionidae (vesper bats) with minimal pixel detail, small brown body, broad wings, and short ears.webp",
    "DALL·E 2025-02-20 21.03.08 - Create a very simple 8-bit pixel art design of Delphinidae (oceanic dolphins) with minimal pixel detail, streamlined grey body, lighter underside, dor.webp",
    "DALL·E 2025-02-20 21.03.10 - Create a very simple 8-bit pixel art design of Grampus griseus (Risso’s dolphin) with minimal pixel detail, grey body with white scarring, lighter und.webp",
    "DALL·E 2025-02-20 21.03.14 - Create a very simple 8-bit pixel art design of Sus scrofa (wild boar) with minimal pixel detail, stocky dark brown body, short legs, bristly fur, and .webp",
    "DALL·E 2025-02-20 21.03.17 - Create a very simple 8-bit pixel art design of Felis catus (domestic cat) with minimal pixel detail, small body, pointed ears, long tail, and whiskers.webp",
    "DALL·E 2025-02-20 21.03.20 - Create a very simple 8-bit pixel art design of Elephantidae (elephants) with minimal pixel detail, large grey body, trunk, tusks, and large ears. Clas.webp",
    "DALL·E 2025-02-20 21.03.22 - Create a very simple 8-bit pixel art design of Nyctalus_Eptesicus agg. (noctule_serotine bat group) with minimal pixel detail, small dark brown body, .webp",
    "DALL·E 2025-02-20 21.03.26 - Create a very simple 8-bit pixel art design of Muridae (mice and rats) with minimal pixel detail, small brown-grey body, long tail, and round ears. Cl.webp",
    "DALL·E 2025-02-20 21.03.29 - Create a very simple 8-bit pixel art design of Myotis brandtii (Brandt’s bat) with minimal pixel detail, small brown body, broad wings, and short ears.webp",
    "DALL·E 2025-02-20 21.03.33 - Create a very simple 8-bit pixel art design of Equus ferus (wild horse) with minimal pixel detail, small brown body, black mane and tail, and slender .webp",
    "DALL·E 2025-02-20 21.03.36 - Create a very simple 8-bit pixel art design of Sciurus (squirrels) with minimal pixel detail, small grey-brown body, bushy tail, and pointed ears. Cla.webp",
    "DALL·E 2025-02-20 21.03.38 - Create a very simple 8-bit pixel art design of Nyctalus (noctule bats) with minimal pixel detail, small brown body, broad dark wings, and short ears. .webp",
    "DALL·E 2025-02-20 21.03.41 - Create a very simple 8-bit pixel art design of Sorex (shrews) with minimal pixel detail, small brown-grey body, pointed snout, short tail, and tiny le.webp",
    "DALL·E 2025-02-20 21.03.43 - Create a very simple 8-bit pixel art design of Crocidura suaveolens (lesser white-toothed shrew) with minimal pixel detail, small grey body, pointed s.webp",
    "DALL·E 2025-02-20 21.03.47 - Create a very simple 8-bit pixel art design of Lagenorhynchus albirostris (white-beaked dolphin) with minimal pixel detail, streamlined dark grey body.webp",
    "DALL·E 2025-02-20 21.03.50 - Create a very simple 8-bit pixel art design of Mustela putorius subsp. furo (domestic ferret) with minimal pixel detail, slender cream-colored body, d.webp",
    "DALL·E 2025-02-20 21.03.53 - Create a very simple 8-bit pixel art design of Mus (mice genus) with minimal pixel detail, small brown-grey body, long tail, and round ears. Classic r.webp",
    "DALL·E 2025-02-20 21.03.58 - Create a very simple 8-bit pixel art design of Myotis bechsteinii (Bechstein’s bat) with minimal pixel detail, small brown body, broad wings, and larg.webp",
    "DALL·E 2025-02-20 21.04.00 - Create a very simple 8-bit pixel art design of Felis silvestris x catus (wildcat_domestic cat hybrid) with minimal pixel detail, striped grey-brown fu.webp",
    "DALL·E 2025-02-20 21.04.04 - Create a very simple 8-bit pixel art design of Mustela furo x putorius (ferret_polecat hybrid) with minimal pixel detail, slender brown body, darker m.webp",
    "DALL·E 2025-02-20 21.04.14 - Create a very simple 8-bit pixel art design of Rattus rattus (black rat) with minimal pixel detail, small black body, long scaly tail, and large round.webp",
    "DALL·E 2025-02-20 21.04.17 - Create a very simple 8-bit pixel art design of Rattus (rats, genus) with minimal pixel detail, small grey-brown body, long tail, and large round ears.webp",
    "DALL·E 2025-02-20 21.04.20 - Create a very simple 8-bit pixel art design of Lepus timidus subsp. hibernicus (Irish hare) with minimal pixel detail, small brownish-grey body, long .webp",
    "DALL·E 2025-02-20 21.04.22 - Create a very simple 8-bit pixel art design of Megaptera novaeangliae (humpback whale) with minimal pixel detail, large dark grey body, lighter unders.webp",
    "DALL·E 2025-02-20 21.04.24 - Create a very simple 8-bit pixel art design of Macropus rufogriseus (red-necked wallaby) with minimal pixel detail, small brownish-grey body, strong h.webp",
    "DALL·E 2025-02-20 21.04.26 - Create a very simple 8-bit pixel art design of Crocidura russula (greater white-toothed shrew) with minimal pixel detail, small brown body, pointed sn.webp",
    "DALL·E 2025-02-20 21.04.29 - Create a very simple 8-bit pixel art design of Rodentia (rodents, order) with minimal pixel detail, a generic rodent figure with small brown body, rou.webp",
    "DALL·E 2025-02-20 21.04.32 - Create a very simple 8-bit pixel art design of Microtus arvalis (common vole) with minimal pixel detail, small brown body, short tail, tiny ears, and .webp",
    "DALL·E 2025-02-20 21.04.34 - Create a very simple 8-bit pixel art design of Cetacea (whales, dolphins, porpoises, order) with minimal pixel detail, a generic cetacean figure with .webp",
    "DALL·E 2025-02-20 21.04.38 - Create a very simple 8-bit pixel art design of Lepus (hares, genus) with minimal pixel detail, a generic hare figure with brown body, long ears with b.webp",
    "DALL·E 2025-02-20 21.04.41 - Create a very simple 8-bit pixel art design of Bison (bison, genus) with minimal pixel detail, large brown body, shaggy mane, curved horns, and sturdy.webp",
    "DALL·E 2025-02-20 21.04.44 - Create a very simple 8-bit pixel art design of Talpidae (moles, family) with minimal pixel detail, small dark body, large front claws, and tiny eyes. .webp",
    "DALL·E 2025-02-20 21.04.48 - Create a very simple 8-bit pixel art design of Mustela erminea subsp. erminea (stoat, nominate subspecies) with minimal pixel detail, small slender br.webp"
];
